// Mock data lembaga/keluarga di desa untuk layar sign-in background.
// Menggantikan `BackgroundMockCompanies` yang masih memakai shape CRM
// (domainName/employees/accountOwner). Sekarang menjelma jadi daftar
// lembaga desa nyata di Sukamaju yang ditampilkan di tabel mock saat
// halaman login.

export type BackgroundMockKeluarga = {
  id: string;
  namaLembaga: string;
  alamat: string;
  pengurus: string | null;
  penanggungJawab: string | null;
  waktuDibuat: string;
  jumlahAnggota: number;
};

export const BACKGROUND_MOCK_KELUARGAS = [
  {
    id: 'bpd-sukamaju',
    namaLembaga: 'BPD Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 2 jam yang lalu',
    jumlahAnggota: 9,
  },
  {
    id: 'pkk-sukamaju',
    namaLembaga: 'PKK Sukamaju',
    alamat: 'Balai PKK Sukamaju',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 3 jam yang lalu',
    jumlahAnggota: 25,
  },
  {
    id: 'bumdes-sukamaju',
    namaLembaga: 'BUMDES Sukamaju Makmur',
    alamat: 'Jl. Raya Desa No. 5',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 5 jam yang lalu',
    jumlahAnggota: 12,
  },
  {
    id: 'karang-taruna',
    namaLembaga: 'Karang Taruna Sukamaju',
    alamat: 'Pemuda Sukamaju',
    pengurus: 'Ahmad Hidayat',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 6 jam yang lalu',
    jumlahAnggota: 40,
  },
  {
    id: 'posyandu-melati',
    namaLembaga: 'Posyandu Melati',
    alamat: 'Dusun Utama',
    pengurus: 'Dewi Lestari',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 7 jam yang lalu',
    jumlahAnggota: 8,
  },
  {
    id: 'kelompok-tani',
    namaLembaga: 'Kelompok Tani Maju',
    alamat: 'Dusun Selatan',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 8 jam yang lalu',
    jumlahAnggota: 35,
  },
  {
    id: 'koperasi-desa',
    namaLembaga: 'Koperasi Desa Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Ahmad Hidayat',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 9 jam yang lalu',
    jumlahAnggota: 5,
  },
  {
    id: 'masjid-al-ikhlas',
    namaLembaga: 'Masjid Al-Ikhlas',
    alamat: 'RW 01',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 10 jam yang lalu',
    jumlahAnggota: 10,
  },
  {
    id: 'sdn-sukamaju',
    namaLembaga: 'SDN Sukamaju 01',
    alamat: 'Dusun Utama',
    pengurus: 'Hendra Wijaya',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 11 jam yang lalu',
    jumlahAnggota: 15,
  },
  {
    id: 'lkmd-sukamaju',
    namaLembaga: 'LKMD Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Ahmad Hidayat',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 12 jam yang lalu',
    jumlahAnggota: 11,
  },
  {
    id: 'polindes-sukamaju',
    namaLembaga: 'Polindes Sukamaju',
    alamat: 'Dusun Mekar',
    pengurus: 'Dewi Lestari',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 13 jam yang lalu',
    jumlahAnggota: 4,
  },
  {
    id: 'paud-ceria',
    namaLembaga: 'PAUD Ceria',
    alamat: 'RW 02',
    pengurus: 'Dewi Lestari',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 14 jam yang lalu',
    jumlahAnggota: 3,
  },
  {
    id: 'kwt-sukamaju',
    namaLembaga: 'Kelompok Wanita Tani',
    alamat: 'Dusun Barat',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 15 jam yang lalu',
    jumlahAnggota: 20,
  },
  {
    id: 'linmas-sukamaju',
    namaLembaga: 'Satuan Linmas Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Hendra Wijaya',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 16 jam yang lalu',
    jumlahAnggota: 15,
  },
  {
    id: 'lembaga-adat',
    namaLembaga: 'Lembaga Adat Desa',
    alamat: 'Rumah Adat Sukamaju',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 17 jam yang lalu',
    jumlahAnggota: 7,
  },
  {
    id: 'forum-rt-rw',
    namaLembaga: 'Forum RT/RW Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Ahmad Hidayat',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 18 jam yang lalu',
    jumlahAnggota: 30,
  },
  {
    id: 'posbindu-sukamaju',
    namaLembaga: 'Posbindu Lansia Sukamaju',
    alamat: 'Dusun Timur',
    pengurus: 'Dewi Lestari',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 19 jam yang lalu',
    jumlahAnggota: 6,
  },
  {
    id: 'tk-bakti',
    namaLembaga: 'TK Bakti Ibu',
    alamat: 'RW 03',
    pengurus: 'Dewi Lestari',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 20 jam yang lalu',
    jumlahAnggota: 4,
  },
  {
    id: 'gapoktan-sukamaju',
    namaLembaga: 'Gapoktan Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Hendra Wijaya',
    penanggungJawab: 'Hendra Wijaya',
    waktuDibuat: 'sekitar 21 jam yang lalu',
    jumlahAnggota: 50,
  },
  {
    id: 'perpustakaan-desa',
    namaLembaga: 'Perpustakaan Desa Sukamaju',
    alamat: 'Balai Desa Sukamaju',
    pengurus: 'Ahmad Hidayat',
    penanggungJawab: 'Dewi Lestari',
    waktuDibuat: 'sekitar 22 jam yang lalu',
    jumlahAnggota: 2,
  },
  {
    id: 'mts-sukamaju',
    namaLembaga: 'MTs Sukamaju',
    alamat: 'Dusun Utama',
    pengurus: 'Drs. H. Abdullah',
    penanggungJawab: 'Ahmad Hidayat',
    waktuDibuat: 'sekitar 23 jam yang lalu',
    jumlahAnggota: 18,
  },
] satisfies BackgroundMockKeluarga[];
