export type BackgroundMockCompany = {
  id: string;
  name: string;
  domainName: string;
  createdBy: string | null;
  accountOwner: string | null;
  creationDate: string;
  employees: number;
  address: string;
};

export const BACKGROUND_MOCK_COMPANIES = [
  {
    id: 'bpd-sukamaju',
    name: 'BPD Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 2 jam yang lalu',
    employees: 9,
    address: 'Sukamaju',
  },
  {
    id: 'pkk-sukamaju',
    name: 'PKK Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 3 jam yang lalu',
    employees: 25,
    address: 'Sukamaju',
  },
  {
    id: 'bumdes-sukamaju',
    name: 'BUMDES Sukamaju Makmur',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 5 jam yang lalu',
    employees: 12,
    address: 'Sukamaju',
  },
  {
    id: 'karang-taruna',
    name: 'Karang Taruna Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Ahmad Hidayat',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 6 jam yang lalu',
    employees: 40,
    address: 'Sukamaju',
  },
  {
    id: 'posyandu-melati',
    name: 'Posyandu Melati',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Dewi Lestari',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 7 jam yang lalu',
    employees: 8,
    address: 'Dusun Utama',
  },
  {
    id: 'kelompok-tani',
    name: 'Kelompok Tani Maju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 8 jam yang lalu',
    employees: 35,
    address: 'Dusun Selatan',
  },
  {
    id: 'koperasi-desa',
    name: 'Koperasi Desa Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Ahmad Hidayat',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 9 jam yang lalu',
    employees: 5,
    address: 'Sukamaju',
  },
  {
    id: 'masjid-al-ikhlas',
    name: 'Masjid Al-Ikhlas',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 10 jam yang lalu',
    employees: 10,
    address: 'RW 001',
  },
  {
    id: 'sdn-sukamaju',
    name: 'SDN Sukamaju 01',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Hendra Wijaya',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 11 jam yang lalu',
    employees: 15,
    address: 'Dusun Utama',
  },
  {
    id: 'lkmd-sukamaju',
    name: 'LKMD Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Ahmad Hidayat',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 12 jam yang lalu',
    employees: 11,
    address: 'Sukamaju',
  },
  {
    id: 'polindes-sukamaju',
    name: 'Polindes Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Dewi Lestari',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 13 jam yang lalu',
    employees: 4,
    address: 'Dusun Mekar',
  },
  {
    id: 'paud-ceria',
    name: 'PAUD Ceria',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Dewi Lestari',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 14 jam yang lalu',
    employees: 3,
    address: 'RW 002',
  },
  {
    id: 'kwt-sukamaju',
    name: 'Kelompok Wanita Tani',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 15 jam yang lalu',
    employees: 20,
    address: 'Dusun Barat',
  },
  {
    id: 'linmas-sukamaju',
    name: 'Satuan Linmas Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Hendra Wijaya',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 16 jam yang lalu',
    employees: 15,
    address: 'Sukamaju',
  },
  {
    id: 'lembaga-adat',
    name: 'Lembaga Adat Desa',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 17 jam yang lalu',
    employees: 7,
    address: 'Sukamaju',
  },
  {
    id: 'forum-rt-rw',
    name: 'Forum RT/RW Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Ahmad Hidayat',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 18 jam yang lalu',
    employees: 30,
    address: 'Sukamaju',
  },
  {
    id: 'posbindu-sukamaju',
    name: 'Posbindu Lansia Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Dewi Lestari',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 19 jam yang lalu',
    employees: 6,
    address: 'Dusun Timur',
  },
  {
    id: 'tk-bakti',
    name: 'TK Bakti Ibu',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Dewi Lestari',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 20 jam yang lalu',
    employees: 4,
    address: 'RW 003',
  },
  {
    id: 'gapoktan-sukamaju',
    name: 'Gapoktan Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Hendra Wijaya',
    accountOwner: 'Hendra Wijaya',
    creationDate: 'sekitar 21 jam yang lalu',
    employees: 50,
    address: 'Sukamaju',
  },
  {
    id: 'perpustakaan-desa',
    name: 'Perpustakaan Desa Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Ahmad Hidayat',
    accountOwner: 'Dewi Lestari',
    creationDate: 'sekitar 22 jam yang lalu',
    employees: 2,
    address: 'Balai Desa',
  },
  {
    id: 'mts-sukamaju',
    name: 'MTs Sukamaju',
    domainName: 'sukamaju.desa.id',
    createdBy: 'Drs. H. Abdullah',
    accountOwner: 'Ahmad Hidayat',
    creationDate: 'sekitar 23 jam yang lalu',
    employees: 18,
    address: 'Dusun Utama',
  },
] satisfies BackgroundMockCompany[];
