export const PAGE_LAYOUT_SEEDS = {
  LAYANAN_DESA_DASHBOARD: 'LAYANAN_DESA_DASHBOARD',
  KEPENDUDUKAN_DASHBOARD: 'KEPENDUDUKAN_DASHBOARD',
  TEAM_DASHBOARD: 'TEAM_DASHBOARD',
  DOCUMENTATION_STANDALONE_PAGE: 'DOCUMENTATION_STANDALONE_PAGE',
};
