import { FieldMetadataType } from 'shared/types';
import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const PERMOHONAN_SURAT_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    label: 'Nomor Permohonan',
    name: 'nomorPermohonan',
    icon: 'IconHash',
    description: 'Nomor registrasi permohonan',
    isUnique: true,
  },
  {
    type: FieldMetadataType.DATE,
    label: 'Tanggal Permohonan',
    name: 'tanggalPermohonan',
    icon: 'IconCalendar',
    description: 'Tanggal pengajuan permohonan',
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status',
    name: 'status',
    icon: 'IconStatusCheck',
    description: 'Status permohonan',
    options: [
      { label: 'Menunggu', value: 'MENUNGGU', position: 0, color: 'yellow' },
      { label: 'Diproses', value: 'DIPROSES', position: 1, color: 'blue' },
      { label: 'Selesai', value: 'SELESAI', position: 2, color: 'green' },
      { label: 'Ditolak', value: 'DITOLAK', position: 3, color: 'red' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Keperluan',
    name: 'keperluan',
    icon: 'IconDescription',
    description: 'Keperluan surat',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Catatan',
    name: 'catatan',
    icon: 'IconNote',
    description: 'Catatan/status lain',
  },
  {
    type: FieldMetadataType.DATE,
    label: 'Tanggal Selesai',
    name: 'tanggalSelesai',
    icon: 'IconCalendar',
    description: 'Tanggal permohonan selesai',
  },
  // Jenis layanan + petugas (modul layanan surat OpenSID)
  {
    type: FieldMetadataType.SELECT,
    label: 'Jenis Layanan',
    name: 'jenisLayanan',
    icon: 'IconCategory',
    description: 'Jenis surat atau layanan yang diminta warga',
    options: [
      { label: 'Domisili', value: 'DOMISILI', position: 0, color: 'blue' },
      { label: 'SKTM', value: 'SKTM', position: 1, color: 'green' },
      {
        label: 'Pengantar Nikah',
        value: 'PENGANTAR_NIKAH',
        position: 2,
        color: 'pink',
      },
      { label: 'SKCK', value: 'SKCK', position: 3, color: 'purple' },
      {
        label: 'Kelahiran',
        value: 'KELAHIRAN',
        position: 4,
        color: 'turquoise',
      },
      { label: 'Kematian', value: 'KEMATIAN', position: 5, color: 'gray' },
      { label: 'Pindah', value: 'PINDAH', position: 6, color: 'orange' },
      { label: 'Datang', value: 'DATANG', position: 7, color: 'yellow' },
      { label: 'Usaha', value: 'USAHA', position: 8, color: 'sky' },
      { label: 'Ahli Waris', value: 'AHLI_WARIS', position: 9, color: 'red' },
      { label: 'Pengaduan', value: 'PENGADUAN', position: 10, color: 'orange' },
      { label: 'Lainnya', value: 'LAINNYA', position: 11, color: 'gray' },
    ],
  },
  {
    type: FieldMetadataType.UUID,
    label: 'ID Petugas',
    name: 'petugasId',
    icon: 'IconUserCog',
    description: 'Referensi ke perangkat desa yang memproses permohonan',
  },
  {
    type: FieldMetadataType.UUID,
    label: 'ID Penduduk Pemohon',
    name: 'pendudukId',
    icon: 'IconUser',
    description: 'Referensi ke penduduk yang mengajukan permohonan',
  },
];
