import { DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID } from '@/page-layout/constants/DefaultTaskRecordPageLayoutId';
import { type PageLayout } from '@/page-layout/types/PageLayout';
import {
  PageLayoutTabLayoutMode,
  PageLayoutType,
  WidgetConfigurationType,
  WidgetType,
} from '~/generated-metadata/graphql';

export const DEFAULT_TASK_RECORD_PAGE_LAYOUT: PageLayout = {
  __typename: 'PageLayout',
  id: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
  name: 'Default Task Layout',
  type: PageLayoutType.RECORD_PAGE,
  objectMetadataId: null,
  universalIdentifier: '00000000-0000-0000-0000-000000000000',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deletedAt: null,
  tabs: [
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: 'task-tab-fields',
      isActive: true,
      title: 'Beranda',
      icon: 'IconHome',
      position: 100,
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'task-widget-fields',
          isActive: true,
          pageLayoutTabId: 'task-tab-fields',
          title: 'Field',
          type: WidgetType.FIELDS,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12,
          },
          position: {
            __typename: 'PageLayoutWidgetVerticalListPosition',
            layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
            index: 0,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'task-widget-note',
          isActive: true,
          pageLayoutTabId: 'task-tab-fields',
          title: 'Catatan',
          type: WidgetType.FIELD_RICH_TEXT,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 12,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          position: {
            __typename: 'PageLayoutWidgetVerticalListPosition',
            layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
            index: 1,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
          conditionalDisplay: {
            and: [
              {
                '===': [{ var: 'device' }, 'MOBILE'],
              },
            ],
          },
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: 'task-tab-note',
      isActive: true,
      title: 'Catatan',
      icon: 'IconNotes',
      position: 150,
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'task-widget-note',
          isActive: true,
          pageLayoutTabId: 'task-tab-note',
          title: 'Catatan',
          type: WidgetType.FIELD_RICH_TEXT,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 12,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          position: {
            __typename: 'PageLayoutWidgetVerticalListPosition',
            layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
            index: 0,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
          conditionalDisplay: {
            and: [
              {
                '===': [{ var: 'device' }, 'DESKTOP'],
              },
            ],
          },
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: 'task-tab-timeline',
      isActive: true,
      title: 'Linimasa',
      icon: 'IconTimelineEvent',
      position: 200,
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'task-widget-timeline',
          isActive: true,
          pageLayoutTabId: 'task-tab-timeline',
          title: 'Linimasa',
          type: WidgetType.TIMELINE,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          position: {
            __typename: 'PageLayoutWidgetCanvasPosition',
            layoutMode: PageLayoutTabLayoutMode.CANVAS,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: 'task-tab-files',
      isActive: true,
      title: 'Berkas',
      icon: 'IconPaperclip',
      position: 300,
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'task-widget-files',
          isActive: true,
          pageLayoutTabId: 'task-tab-files',
          title: 'Berkas',
          type: WidgetType.FILES,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          position: {
            __typename: 'PageLayoutWidgetCanvasPosition',
            layoutMode: PageLayoutTabLayoutMode.CANVAS,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
    },
  ],
};
