/*
 * ____            _
 *| __ )  __ _  __| | ___  ___
 *|  _ \ / _` |/ _` |/ _ \/ __|   Auto-generated file
 *| |_) | (_| | (_| |  __/\__ \   Any edits to this will be overridden
 *|____/ \__,_|\__,_|\___||___/   Generated by: bunx nx version:bump server
 */

export const BADES_CURRENT_VERSION = '2.7.0' as const;
