/*
 * _____                    _
 *|_   _|_      _____ _ __ | |_ _   _
 *  | | \ \ /\ / / _ \ '_ \| __| | | | Auto-generated file
 *  | |  \ V  V /  __/ | | | |_| |_| | Any edits to this will be overridden
 *  |_|   \_/\_/ \___|_| |_|\__|\__, | Generated by: npx nx version:bump bades-server
 *                              |___/
 */

export const BADES_NEXT_VERSIONS = [
  '2.8.0',
] as const;
