/*
 * ____            _
 *| __ )  __ _  __| | ___  ___
 *|  _ \ / _` |/ _` |/ _ \/ __|   Auto-generated file
 *| |_) | (_| | (_| |  __/\__ \   Any edits to this will be overridden
 *|____/ \__,_|\__,_|\___||___/   Generated by: bunx nx version:bump server
 */

export const BADES_PREVIOUS_VERSIONS = [
  '1.21.0',
  '1.22.0',
  '1.23.0',
  '2.0.0',
  '2.1.0',
  '2.2.0',
  '2.3.0',
  '2.4.0',
  '2.5.0',
  '2.6.0',
] as const;
