export enum CoreObjectNameSingular {
  Activity = 'activity',
  ActivityTarget = 'activityTarget',
  ApiKey = 'apiKey',
  Attachment = 'attachment',
  Blocklist = 'blocklist',
  CalendarChannel = 'calendarChannel',
  CalendarEvent = 'calendarEvent',
  Comment = 'comment',
  // Bades: Company/Person/Opportunity dipertahankan sebagai enum value
  // kompatibilitas untuk consumer legacy (page-layout defaults, activity
  // resolver) — TIDAK lagi ada object aktif di STANDARD_OBJECTS. SID
  // equivalent: keluarga (KK), penduduk, programBantuan.
  Company = 'company',
  ConnectedAccount = 'connectedAccount',
  Dashboard = 'dashboard',
  TimelineActivity = 'timelineActivity',
  Message = 'message',
  MessageChannel = 'messageChannel',
  MessageParticipant = 'messageParticipant',
  MessageFolder = 'messageFolder',
  MessageThread = 'messageThread',
  Note = 'note',
  NoteTarget = 'noteTarget',
  Opportunity = 'opportunity',
  Person = 'person',
  Task = 'task',
  TaskTarget = 'taskTarget',
  Webhook = 'webhook',
  WorkspaceMember = 'workspaceMember',
  MessageThreadSubscriber = 'messageThreadSubscriber',
  Workflow = 'workflow',
  MessageChannelMessageAssociation = 'messageChannelMessageAssociation',
  WorkflowVersion = 'workflowVersion',
  WorkflowRun = 'workflowRun',
}
