name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

env:
  BADES_VERSION: latest

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spawn Bades test instance
        id: bades
        uses: badesid/bades/.github/actions/spawn-bades-app-dev-test@main
        with:
          bades-version: ${{ env.BADES_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run integration tests
        run: yarn test
        env:
          BADES_API_URL: ${{ steps.bades.outputs.server-url }}
          BADES_API_KEY: ${{ steps.bades.outputs.api-key }}
