apiVersion: v1
kind: PersistentVolume
metadata:
  name: bades-server-pv
  namespace: bades
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
