apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bades-db-pvc
  namespace: bades
spec:
  storageClassName: default
  volumeName: bades-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
