apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bades-server-pvc
  namespace: bades
spec:
  storageClassName: default
  volumeName: bades-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
