apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bades-docker-data-pvc
  namespace: bades
spec:
  storageClassName: default
  volumeName: bades-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
