version: "3.8"

services:
  db:
    container_name: bades-db
    image: postgres:16
    environment:
      POSTGRES_DB: bades
      POSTGRES_USER: bades
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
    volumes:
      - bades-db-data:/var/lib/postgresql/data:Z

  redis:
    container_name: bades-redis
    image: redis:latest
    command: ["--maxmemory-policy", "noeviction"]
    volumes:
      - bades-redis-data:/data:Z

  server:
    container_name: bades-server
    image: badesid/bades:latest
    environment:
      NODE_PORT: "3000"
      SERVER_URL: ${SERVER_URL}
      PG_DATABASE_URL: "postgresql://bades:${PG_DATABASE_PASSWORD}@bades-db:5432/bades"
      REDIS_URL: "redis://bades-redis:6379"
      APP_SECRET: ${APP_SECRET}
      NODE_ENV: production
      LOG_LEVEL: info
    volumes:
      - bades-server-data:/app/docker-data:Z
    ports:
      - 127.0.0.1:8080:3000

  worker:
    container_name: bades-worker
    image: badesid/bades:latest
    command: yarn worker:prod
    environment:
      SERVER_URL: ${SERVER_URL}
      PG_DATABASE_URL: "postgresql://bades:${PG_DATABASE_PASSWORD}@bades-db:5432/bades"
      REDIS_URL: "redis://bades-redis:6379"
      APP_SECRET: ${APP_SECRET}
      DISABLE_DB_MIGRATIONS: "true"
      NODE_ENV: production
      LOG_LEVEL: info
    volumes:
      - bades-server-data:/app/docker-data:Z
    init: true

volumes:
  bades-db-data:
  bades-server-data:
  bades-redis-data:
