import { FieldMetadataType } from 'shared/types';
import { type FieldMetadataSeed } from 'src/engine/workspace-manager/sid-standard-seed/constants/types/field-metadata-seed.type';

export const PENDUDUK_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    label: 'NIK',
    name: 'nik',
    description: 'Nomor Induk Kependudukan (16 digit)',
    isUnique: true,
  },
  {
    type: FieldMetadataType.FULL_NAME,
    label: 'Nama Lengkap',
    name: 'namaLengkap',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Tempat Lahir',
    name: 'tempatLahir',
  },
  {
    type: FieldMetadataType.DATE,
    label: 'Tanggal Lahir',
    name: 'tanggalLahir',
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Jenis Kelamin',
    name: 'jenisKelamin',
    options: [
      { label: 'Laki-laki', value: 'LAKI_LAKI', position: 0 },
      { label: 'Perempuan', value: 'PEREMPUAN', position: 1 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Agama',
    name: 'agama',
    options: [
      { label: 'Islam', value: 'ISLAM', position: 0 },
      { label: 'Kristen', value: 'KRISTEN', position: 1 },
      { label: 'Katholik', value: 'KATHOLIK', position: 2 },
      { label: 'Hindu', value: 'HINDU', position: 3 },
      { label: 'Buddha', value: 'BUDDHA', position: 4 },
      { label: 'Konghucu', value: 'KONGHUCU', position: 5 },
      {
        label: 'Penghayat Kepercayaan',
        value: 'PENGHAYAT_KEPERCAYAAN',
        position: 6,
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status Perkawinan',
    name: 'statusPerkawinan',
    options: [
      { label: 'Belum Kawin', value: 'BELUM_KAWIN', position: 0 },
      { label: 'Kawin', value: 'KAWIN', position: 1 },
      { label: 'Cerai Hidup', value: 'CERAI_HIDUP', position: 2 },
      { label: 'Cerai Mati', value: 'CERAI_MATI', position: 3 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Pendidikan',
    name: 'pendidikan',
    options: [
      { label: 'Tidak/Belum Sekolah', value: 'TIDAK_SEKOLAH', position: 0 },
      { label: 'SD/Sederajat', value: 'SD', position: 1 },
      { label: 'SMP/Sederajat', value: 'SMP', position: 2 },
      { label: 'SMA/Sederajat', value: 'SMA', position: 3 },
      { label: 'D1', value: 'D1', position: 4 },
      { label: 'D2', value: 'D2', position: 5 },
      { label: 'D3', value: 'D3', position: 6 },
      { label: 'S1', value: 'S1', position: 7 },
      { label: 'S2', value: 'S2', position: 8 },
      { label: 'S3', value: 'S3', position: 9 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Pekerjaan',
    name: 'pekerjaan',
    description: 'Jenis pekerjaan sesuai nomenklatur BPS/Dukcapil',
    options: [
      {
        label: 'Belum/Tidak Bekerja',
        value: 'TIDAK_BEKERJA',
        position: 0,
      },
      {
        label: 'Pelajar/Mahasiswa',
        value: 'PELAJAR_MAHASISWA',
        position: 1,
      },
      { label: 'PNS', value: 'PNS', position: 2 },
      { label: 'TNI', value: 'TNI', position: 3 },
      { label: 'Polri', value: 'POLRI', position: 4 },
      {
        label: 'Petani/Pekebun',
        value: 'PETANI',
        position: 5,
      },
      {
        label: 'Buruh Tani',
        value: 'BURUH_TANI',
        position: 6,
      },
      { label: 'Nelayan', value: 'NELAYAN', position: 7 },
      {
        label: 'Wiraswasta',
        value: 'WIRASWASTA',
        position: 8,
      },
      {
        label: 'Pedagang',
        value: 'PEDAGANG',
        position: 9,
      },
      {
        label: 'Karyawan Swasta',
        value: 'KARYAWAN_SWASTA',
        position: 10,
      },
      { label: 'Guru', value: 'GURU', position: 11 },
      { label: 'Dosen', value: 'DOSEN', position: 12 },
      {
        label: 'Bidan/Perawat',
        value: 'BIDAN_PERAWAT',
        position: 13,
      },
      { label: 'Dokter', value: 'DOKTER', position: 14 },
      { label: 'Sopir', value: 'SOPIR', position: 15 },
      {
        label: 'Buruh Harian',
        value: 'BURUH_HARIAN',
        position: 16,
      },
      {
        label: 'Pensiunan',
        value: 'PENSIUNAN',
        position: 17,
      },
      {
        label: 'Ibu Rumah Tangga',
        value: 'IBU_RUMAH_TANGGA',
        position: 18,
      },
      { label: 'Lainnya', value: 'LAINNYA', position: 19 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Golongan Darah',
    name: 'golonganDarah',
    options: [
      { label: 'A', value: 'A', position: 0 },
      { label: 'B', value: 'B', position: 1 },
      { label: 'AB', value: 'AB', position: 2 },
      { label: 'O', value: 'O', position: 3 },
      { label: 'Tidak Tahu', value: 'TIDAK_TAHU', position: 4 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Kewarganegaraan',
    name: 'kewarganegaraan',
    options: [
      { label: 'WNI', value: 'WNI', position: 0 },
      { label: 'WNA', value: 'WNA', position: 1 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status Hubungan dalam Keluarga',
    name: 'statusHubunganKeluarga',
    options: [
      { label: 'Kepala Keluarga', value: 'KEPALA_KELUARGA', position: 0 },
      { label: 'Suami', value: 'SUAMI', position: 1 },
      { label: 'Istri', value: 'ISTRI', position: 2 },
      { label: 'Anak', value: 'ANAK', position: 3 },
      { label: 'Menantu', value: 'MENANTU', position: 4 },
      { label: 'Cucu', value: 'CUCU', position: 5 },
      { label: 'Orang Tua', value: 'ORANG_TUA', position: 6 },
      { label: 'Mertua', value: 'MERTUA', position: 7 },
      { label: 'Famili Lain', value: 'FAMILI_LAIN', position: 8 },
      { label: 'Pembantu', value: 'PEMBANTU', position: 9 },
      { label: 'Lainnya', value: 'LAINNYA', position: 10 },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status Kependudukan',
    name: 'statusKependudukan',
    description: 'Status kependudukan warga di desa',
    options: [
      { label: 'Menetap', value: 'MENETAP', position: 0 },
      {
        label: 'Pendatang',
        value: 'PENDATANG',
        position: 1,
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Status Dasar',
    name: 'statusDasar',
    description: 'Status dasar kependudukan (Hidup/Meninggal/Pindah/Hilang)',
    options: [
      { label: 'Hidup', value: 'HIDUP', position: 0 },
      {
        label: 'Meninggal',
        value: 'MENINGGAL',
        position: 1,
      },
      { label: 'Pindah', value: 'PINDAH', position: 2 },
      { label: 'Hilang', value: 'HILANG', position: 3 },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'NIK Ayah',
    name: 'nikAyah',
    description: 'NIK Ayah Kandung',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'NIK Ibu',
    name: 'nikIbu',
    description: 'NIK Ibu Kandung',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Nama Ayah',
    name: 'namaAyah',
    description: 'Nama lengkap ayah kandung',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'Nama Ibu',
    name: 'namaIbu',
    description: 'Nama lengkap ibu kandung',
  },
  {
    type: FieldMetadataType.TEXT,
    label: 'No. Akta Kelahiran',
    name: 'noAktaKelahiran',
    description: 'Nomor akta kelahiran dari Dukcapil',
  },
  {
    type: FieldMetadataType.SELECT,
    label: 'Penyandang Disabilitas',
    name: 'penyandangDisabilitas',
    description: 'Jenis disabilitas (jika ada)',
    options: [
      {
        label: 'Tidak Ada',
        value: 'TIDAK_ADA',
        position: 0,
      },
      {
        label: 'Cacat Fisik',
        value: 'CACAT_FISIK',
        position: 1,
      },
      {
        label: 'Cacat Netra/Buta',
        value: 'CACAT_NETRA',
        position: 2,
      },
      {
        label: 'Cacat Rungu/Wicara',
        value: 'CACAT_RUNGU_WICARA',
        position: 3,
      },
      {
        label: 'Cacat Mental/Jiwa',
        value: 'CACAT_MENTAL',
        position: 4,
      },
      {
        label: 'Cacat Ganda (Fisik & Mental)',
        value: 'CACAT_GANDA',
        position: 5,
      },
    ],
  },
  {
    type: FieldMetadataType.PHONES,
    label: 'Nomor HP',
    name: 'noHp',
    description: 'Nomor telepon genggam penduduk',
  },
  {
    type: FieldMetadataType.EMAILS,
    label: 'Email',
    name: 'email',
    description: 'Alamat email penduduk',
  },
  {
    type: FieldMetadataType.DATE,
    label: 'Tanggal Meninggal',
    name: 'tanggalMeninggal',
    description:
      'Tanggal meninggal dunia (diisi jika statusDasar = Meninggal)',
  },
  {
    type: FieldMetadataType.FILES,
    label: 'Foto',
    name: 'foto',
    description: 'Foto penduduk (berkas, bukan tautan)',
    settings: { maxNumberOfValues: 1 },
  },
  {
    type: FieldMetadataType.DATE,
    label: 'Tanggal Sinkronisasi Dukcapil',
    name: 'tanggalSinkronisasiDukcapil',
    description: 'Tanggal terakhir data disinkronkan dengan Dukcapil',
  },
];
