import { msg } from '@lingui/core/macro';

import type { WebsiteRoute } from './types';

export const STATIC_WEBSITE_ROUTES = [
  {
    id: 'home',
    path: '/',
    title: msg`Bades.id | Sistem Informasi Desa Open Source`,
    description: msg`Sistem Informasi Desa (SID) open source untuk pemerintahan balai desa di Indonesia. Modular, scalable, dan built untuk kebutuhan desa Anda.`,
    changeFrequency: 'weekly',
    priority: 1,
    indexed: true,
  },
  {
    id: 'whyBades',
    path: '/why-bades',
    title: msg`Why Bades.id — The Open Source Village Information System Built to Be Customised`,
    description: msg`Packaged village administration systems make every village look the same. Bades.id is the open source SID teams shape around their workflow, with a modern UI and a developer-first platform.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'product',
    path: '/product',
    title: msg`Bades.id Features — Modern Open Source Village Administration System`,
    description: msg`Service pipelines, custom objects, AI assistants, and a native API on top of Postgres. Bades.id is the open source SID with the modern UX villages actually want to use.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'pricing',
    path: '/pricing',
    title: msg`Bades.id Pricing — Plans for Indonesian Villages`,
    description: msg`Cloud Pro starts at Rp 90.000/user/month with unlimited custom objects. Self-host the open source core for free, or upgrade to Organization for SSO and row-level permissions.`,
    changeFrequency: 'monthly',
    priority: 0.9,
    indexed: true,
  },
  {
    id: 'partners',
    path: '/partners',
    title: msg`Bades.id Partners — Certified Open Source SID Implementers`,
    description: msg`Find a certified Bades.id partner to migrate, customise, and operate your open source SID, or join the ecosystem and grow your practice with us.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'releases',
    path: '/releases',
    title: msg`Bades.id Releases — What's New in the Open Source SID`,
    description: msg`Every new release of Bades.id, the open source Village Information System, with changelogs, demos, and the highlights teams care about most.`,
    changeFrequency: 'weekly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'customers',
    path: '/customers',
    title: msg`Bades.id Customers — How Modern Villages Run Their Administration`,
    description: msg`Real customer stories from villages running their administration on Bades.id: how they migrated, what they customised, and what changed once their SID finally fit.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'articles',
    path: '/articles',
    title: msg`Bades.id Articles — Open Source SID Insights`,
    description: msg`Ideas from the team building Bades.id on open source SID, village data, administration systems, and building software that lasts.`,
    changeFrequency: 'daily',
    priority: 0.8,
    indexed: true,
    localeMode: 'source',
  },
  {
    id: 'privacyPolicy',
    path: '/privacy-policy',
    title: msg`Privacy Policy | Bades.id`,
    description: msg`How Bades.id collects, uses, safeguards, and discloses information when you use Bades.id and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'terms',
    path: '/terms',
    title: msg`Terms of Service | Bades.id`,
    description: msg`Terms of Service for Bades.id, including use of Bades.id, sub-domains, and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'halftone',
    path: '/halftone',
    title: msg`Halftone Generator | Bades.id`,
    description: msg`Interactive halftone generator exported from Bades.id.`,
    changeFrequency: 'monthly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
  {
    id: 'enterpriseActivate',
    path: '/enterprise/activate',
    title: msg`Enterprise Activation | Bades.id`,
    description: msg`Complete activation for your Bades.id self-hosted enterprise license.`,
    changeFrequency: 'yearly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
] as const satisfies readonly WebsiteRoute[];