export const CHART_CONFIGURATION_SETTING_LABELS = {
  SOURCE: `Sumber`,
  DATA_LABELS: `Label data`,
  CENTER_METRIC: `Tampilkan nilai di tengah`,
  COLORS: `Warna`,
  FILTER: `Filter`,
  GROUP_BY: `Kelompokkan berdasarkan`,
  PRIMARY_SORT_BY: `Urutkan berdasarkan`,
  SORT_BY_GROUP_BY_FIELD: `Urutkan berdasarkan`,
  DATA_ON_DISPLAY_X: `Data yang ditampilkan`,
  DATA_ON_DISPLAY_Y: `Data yang ditampilkan`,
  DATA_ON_DISPLAY_PIE_CHART: `Data yang ditampilkan`,
  DATA_ON_DISPLAY_AGGREGATE: `Data yang ditampilkan`,
  EACH_SLICE_REPRESENTS: `Setiap irisan mewakili`,
  AXIS_NAME: `Nama sumbu`,
  STACKED_BARS: `Batang bertumpuk`,
  STACKED_LINES: `Garis bertumpuk`,
  OMIT_NULL_VALUES: `Abaikan nilai nol`,
  HIDE_EMPTY_CATEGORY: `Sembunyikan kategori kosong`,
  MIN_RANGE: `Rentang minimum`,
  MAX_RANGE: `Rentang maksimum`,
  DATE_GRANULARITY_X: `Granularitas tanggal`,
  DATE_GRANULARITY_Y: `Granularitas tanggal`,
  DATE_GRANULARITY: `Granularitas tanggal`,
  SHOW_LEGEND: `Legenda`,
  PREFIX: `Awalan`,
  SUFFIX: `Akhiran`,
  CUMULATIVE: `Kumulatif`,
  SPLIT_MULTI_VALUE_FIELDS_X: `Pisahkan beberapa nilai`,
  SPLIT_MULTI_VALUE_FIELDS_Y: `Pisahkan beberapa nilai`,
};
