import { msg } from '@lingui/core/macro';

export const CHART_CONFIGURATION_SETTING_LABELS = {
  SOURCE: "Sumber",
  DATA_LABELS: ""Data labels",
  CENTER_METRIC: ""Show value in center",
  COLORS: ""Colors",
  FILTER: msg`Filter`,
  GROUP_BY: "Kelompokkan berdasarkan",
  PRIMARY_SORT_BY: "Urutkan berdasarkan",
  SORT_BY_GROUP_BY_FIELD: "Urutkan berdasarkan",
  DATA_ON_DISPLAY_X: ""Data on display",
  DATA_ON_DISPLAY_Y: ""Data on display",
  DATA_ON_DISPLAY_PIE_CHART: ""Data on display",
  DATA_ON_DISPLAY_AGGREGATE: ""Data on display",
  EACH_SLICE_REPRESENTS: ""Each slice represents",
  AXIS_NAME: ""Axis name",
  STACKED_BARS: ""Stacked bars",
  STACKED_LINES: ""Stacked lines",
  OMIT_NULL_VALUES: ""Omit zero values",
  HIDE_EMPTY_CATEGORY: ""Hide empty category",
  MIN_RANGE: ""Min range",
  MAX_RANGE: ""Max range",
  DATE_GRANULARITY_X: ""Date granularity",
  DATE_GRANULARITY_Y: ""Date granularity",
  DATE_GRANULARITY: ""Date granularity",
  SHOW_LEGEND: ""Legend",
  PREFIX: ""Prefix",
  SUFFIX: ""Suffix",
  CUMULATIVE: ""Cumulative",
  SPLIT_MULTI_VALUE_FIELDS_X: ""Split multiple values",
  SPLIT_MULTI_VALUE_FIELDS_Y: ""Split multiple values",
};
