import { msg } from '~/utils/i18n/badesI18n';

export const CHART_CONFIGURATION_SETTING_LABELS = {
  SOURCE: msg`Sumber`,
  DATA_LABELS: msg`Label data`,
  CENTER_METRIC: msg`Tampilkan nilai di tengah`,
  COLORS: msg`Warna`,
  FILTER: msg`Filter`,
  GROUP_BY: msg`Kelompokkan berdasarkan`,
  PRIMARY_SORT_BY: msg`Urutkan berdasarkan`,
  SORT_BY_GROUP_BY_FIELD: msg`Urutkan berdasarkan`,
  DATA_ON_DISPLAY_X: msg`Data yang ditampilkan`,
  DATA_ON_DISPLAY_Y: msg`Data yang ditampilkan`,
  DATA_ON_DISPLAY_PIE_CHART: msg`Data yang ditampilkan`,
  DATA_ON_DISPLAY_AGGREGATE: msg`Data yang ditampilkan`,
  EACH_SLICE_REPRESENTS: msg`Setiap irisan mewakili`,
  AXIS_NAME: msg`Nama sumbu`,
  STACKED_BARS: msg`Batang bertumpuk`,
  STACKED_LINES: msg`Garis bertumpuk`,
  OMIT_NULL_VALUES: msg`Abaikan nilai nol`,
  HIDE_EMPTY_CATEGORY: msg`Sembunyikan kategori kosong`,
  MIN_RANGE: msg`Rentang minimum`,
  MAX_RANGE: msg`Rentang maksimum`,
  DATE_GRANULARITY_X: msg`Granularitas tanggal`,
  DATE_GRANULARITY_Y: msg`Granularitas tanggal`,
  DATE_GRANULARITY: msg`Granularitas tanggal`,
  SHOW_LEGEND: msg`Legenda`,
  PREFIX: msg`Awalan`,
  SUFFIX: msg`Akhiran`,
  CUMULATIVE: msg`Kumulatif`,
  SPLIT_MULTI_VALUE_FIELDS_X: msg`Pisahkan beberapa nilai`,
  SPLIT_MULTI_VALUE_FIELDS_Y: msg`Pisahkan beberapa nilai`,
};
