import {
  CommandMenuItemAvailabilityType,
  type CommandMenuItemFieldsFragment,
  EngineComponentKey,
} from '~/generated-metadata/graphql';

export const mockedBackendCommandMenuItems: CommandMenuItemFieldsFragment[] = [
  {
    __typename: 'CommandMenuItem',
    id: 'mock-go-to-people',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.GO_TO_PEOPLE,
    label: 'Ke Penduduk',
    icon: 'IconUser',
    shortLabel: 'Penduduk',
    position: 23,
    isPinned: false,
    hotKeys: ['G', 'P'],
    conditionalAvailabilityExpression: 'targetObjectReadPermissions.person',
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-go-to-opportunities',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.GO_TO_OPPORTUNITIES,
    label: 'Ke Permohonan',
    icon: 'IconTargetArrow',
    shortLabel: 'Permohonan',
    position: 26,
    isPinned: false,
    hotKeys: ['G', 'O'],
    conditionalAvailabilityExpression:
      'targetObjectReadPermissions.opportunity',
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-go-to-settings',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.GO_TO_SETTINGS,
    label: 'Ke Pengaturan',
    icon: 'IconSettings',
    shortLabel: 'Pengaturan',
    position: 27,
    isPinned: false,
    hotKeys: ['G', 'S'],
    conditionalAvailabilityExpression: null,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-go-to-tasks',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.GO_TO_TASKS,
    label: 'Ke Tugas',
    icon: 'IconCheckbox',
    shortLabel: 'Tugas',
    position: 28,
    isPinned: false,
    hotKeys: ['G', 'T'],
    conditionalAvailabilityExpression: 'targetObjectReadPermissions.task',
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-go-to-notes',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.GO_TO_NOTES,
    label: 'Ke Catatan',
    icon: 'IconCheckbox',
    shortLabel: 'Catatan',
    position: 29,
    isPinned: false,
    hotKeys: ['G', 'N'],
    conditionalAvailabilityExpression: 'targetObjectReadPermissions.note',
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-search-records',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.SEARCH_RECORDS,
    label: 'Search ${capitalize(objectMetadataItem.labelPlural)}',
    icon: 'IconSearch',
    shortLabel: 'Search',
    position: 60,
    isPinned: false,
    hotKeys: ['/'],
    conditionalAvailabilityExpression: null,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-search-records-fallback',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.SEARCH_RECORDS_FALLBACK,
    label: 'Search ${capitalize(objectMetadataItem.labelPlural)}',
    icon: 'IconSearch',
    shortLabel: 'Search',
    position: 61,
    isPinned: false,
    hotKeys: ['/'],
    conditionalAvailabilityExpression: null,
    availabilityType: CommandMenuItemAvailabilityType.FALLBACK,
    availabilityObjectMetadataId: null,
  },
];
