import {
  CommandMenuItemAvailabilityType,
  type CommandMenuItemFieldsFragment,
  EngineComponentKey,
} from '~/generated-metadata/graphql';

export const mockedBackendCommandMenuItems: CommandMenuItemFieldsFragment[] = [
  {
    __typename: 'CommandMenuItem',
    id: 'mock-search-records',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.SEARCH_RECORDS,
    label: 'Cari ${capitalize(objectMetadataItem.labelPlural)}',
    icon: 'IconSearch',
    shortLabel: 'Cari',
    position: 60,
    isPinned: false,
    hotKeys: ['/'],
    conditionalAvailabilityExpression: null,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    availabilityObjectMetadataId: null,
  },
  {
    __typename: 'CommandMenuItem',
    id: 'mock-search-records-fallback',
    workflowVersionId: null,
    frontComponentId: null,
    frontComponent: null,
    engineComponentKey: EngineComponentKey.SEARCH_RECORDS_FALLBACK,
    label: 'Cari ${capitalize(objectMetadataItem.labelPlural)}',
    icon: 'IconSearch',
    shortLabel: 'Cari',
    position: 61,
    isPinned: false,
    hotKeys: ['/'],
    conditionalAvailabilityExpression: null,
    availabilityType: CommandMenuItemAvailabilityType.FALLBACK,
    availabilityObjectMetadataId: null,
  },
];
